
#General Configs
[general]
	GET_STARTER_ITEMS = true
	loot_announcements = true
	require_team_for_dungeons = true
	dont_sync_ambient_mob_data = true
	SCALE_MOB_LEVEL_TO_NEAREST_PLAYER = true
	maps_dont_drop_in_maps = true
	log_errors = true
	stop_error_spam = true
	STATION_SUCK_NEARBY_CHESTS = false
	#Mobs that are much higher level will hide their levels.
	SKULL_HIDES_LEVEL = true
	#Do not change this
	FORCE_SURVIVAL_MODE_OUTSIDE_MAP = true
	#Mns tries to replicate vanilla atk speed and reduces dmg of basic attacks if hit too often
	REMOVE_ATK_SPEED_COOLDOWN = false
	#Range: > 0
	min_level_map_drops = 25
	#Range: > 0
	MIN_SLIME_SIZE_FOR_LOOT = 3
	#Range: > 0
	DEATH_PENALTY_START_LEVEL = 25
	#Range: > 0
	LEVEL_DISTANCE_PENALTY_LEEWAY = 2
	#Range: 0 ~ 100
	PERC_OFFHAND_WEP_STAT = 25
	#Range: 0.0 ~ 1000.0
	regen_hunger_cost = 10.0
	#Range: 0.0 ~ 1.0
	death_exp_penalty = 0.1
	#Range: 0.0 ~ 1.0
	death_exp_debt = 0.1
	#Range: 0.0 ~ 100.0
	max_death_exp_debt_multi = 1.0
	#Range: 0.0 ~ 1000.0
	exp_gain_multi = 1.0
	#Range: 0.0 ~ 1000.0
	party_radius = 200.0
	#When mobs are this many levels higher than you, a skull will show, indicating danger.
	#Range: 1 ~ 1000
	SHOW_SKULL_ON_MOBS_THAT_ARE_X_LEVELS_HIGHER_THAN_YOU = 5
	#When you are higher or lower level than mobs by X levels, decreases the loot and exp droprate.
	#Range: 0.0 ~ 1.0
	lvl_distance_loot_penalty_per_level = 0.2
	#Range: 0.0 ~ 1.0
	min_loot_chance = 0.2
	#Range: 0.0 ~ 1000.0
	extra_mob_stats_per_lvl = 0.02
	#Range: 0.0 ~ 1000.0
	vanilla_mob_dmg_as_exile_dmg = 1.0
	#Range: 0.0 ~ 10.0
	pvp_dmg_multi = 1.0
	#Range: 0.0 ~ 100000.0
	max_team_distance = 75.0
	#Distance needed from player to despawn mobs in maps, lower means more despawning
	#Range: 5.0 ~ 200.0
	MOB_DESPAWN_DISTANCE_IN_MAPS = 30.0
	#Range: 5.0 ~ 99.0
	MAP_PERCENT_COMPLETE_NEEDED_FOR_BOSS_ARENA = 50.0
	#Range: 0.0 ~ 10.0
	in_combat_regen_multi = 0.5
	#Range: 0.0 ~ 1.0
	COMBAT_TO_PROFESSION_RESTED_XP_GENERATION = 0.25
	#Range: 0.0 ~ 1.0
	PROFESSION_TO_COMBAT_RESTED_XP_GENERATION = 0.1
	#Range: 0.0 ~ 1.0
	RESTED_XP_DEATH_PENALTY = 0.5
	#Range: 0.0 ~ 10000.0
	favor_death_loss = 50.0
	#Range: 0 ~ 10000000
	MAX_POSSIBLE_FAVOR = 10000000
	#Range: 0.0 ~ 10000.0
	favor_chest_gain = 1.0
	#Range: 0.0 ~ 1000.0
	gear_drop_rate = 7.0
	#Range: 0.0 ~ 1000.0
	soul_drop_rate = 0.3
	#Range: 0.0 ~ 1000.0
	gem_drop_rate = 1.0
	#Range: 0.0 ~ 1000.0
	UBER_FRAG_DROP_RATE = 10.0
	#Range: 0.0 ~ 1000.0
	skill_gem_drop_rate = 3.0
	#Range: 0.0 ~ 1000.0
	support_gem_drop_rate = 2.0
	#Range: 0.0 ~ 1000.0
	aura_gem_drop_rate = 2.0
	#Range: 0.0 ~ 1000.0
	rune_drop_rate = 0.5
	#Range: 0.0 ~ 1000.0
	currency_drop_rate = 1.0
	#Range: 0.0 ~ 1000.0
	WATCHER_EYE_DROPRATE = 33.0
	#Range: 0.0 ~ 1000.0
	PROPHECY_COIN_DROPRATE = 1.0
	#Range: 0.0 ~ 1000.0
	jewel_drop_rate = 0.25
	#Range: 0.0 ~ 1000.0
	loot_chest_drop_rate = 0.1
	#Range: 0.0 ~ 1000.0
	OMEN_DROPRATE = 0.1
	#Range: 0.0 ~ 1000.0
	block_cost = 0.25
	#Range: 0 ~ 20
	pack_mob_min = 3
	#Range: 0 ~ 20
	pack_mob_max = 6
	#Range: 0 ~ 6
	MAP_GEN_MOB_RADIUS = 1
	#Range: 0 ~ 10
	MAP_GEN_TERRAIN_RADIUS = 4
	#Range: 1 ~ 100
	MIN_MAP_ROOMS = 12
	#Range: 1 ~ 100
	MAX_MAP_ROOMS = 20
	#Range: 0 ~ 100
	ITEM_LEVEL_VARIANCE = 3
	#Range: 0 ~ 100
	MOB_LEVEL_VARIANCE = 3
	#Range: 1 ~ 18
	PROPHECY_OFFERS_PER_REROLL = 18
	#Range: 0 ~ 20
	mob_min = 1
	#Range: 0 ~ 20
	mob_max = 2
	#Range: 0 ~ 1000
	BONUS_EXP_PERCENT_PER_HIGHER_LVL_CHARACTERS = 10
	#Range: 1 ~ 7
	MAX_CHARACTERS = 3
	#Range: 0.0 ~ 100.0
	UNARMED_ENERGY_COST = 10.0
	#This is for modded gear that can't be automatically recognized by the mod. If there's say a weapon like a staff in another mod, but this mod doesn't recognize it. Put it here. The usage is: modid:path:gear_slot_id. Example: minecraft:diamond_sword:sword
	gear_compatibility = ["minecraft:iron_sword:sword", "legendary_monsters:mossy_hammer:hammer", "legendary_monsters:axe_of_lightning:axe", "legendary_monsters:withered_scythe:scythe", "legendary_monsters:wand_of_clouds:hammer", "born_in_chaos_v1:wood_splitter_axe:axe", "born_in_chaos_v1:sweet_axe:axe", "born_in_chaos_v1:great_reaper_axe:axe", "born_in_chaos_v1:pumpkin_staff:staff", "born_in_chaos_v1:bonescaller_staff_:staff", "born_in_chaos_v1:staff_of_magic_arrows:bow", "cataclysm:wrath_of_the_desert:bow", "cataclysm:cursed_bow:bow", "cataclysm:gauntlet_of_guard:gauntlet", "cataclysm:gauntlet_of_maelstrom:gauntlet", "cataclysm:bulwark_of_the_flame:shield", "cataclysm:infernal_forge:hammer", "cataclysm:the_immolator:hammer", "cataclysm:the_annihilator:hammer", "cataclysm:meat_sheredder:sword", "cataclysm:wither_assault_shoulder_weapon:crossbow", "cataclysm:void_assault_shoulder_weapon:crossbow", "cataclysm:the_incinerator:greatsword", "cataclysm:ancient_spear:spear", " cataclysm:gauntlet_of_bulwark:gauntlet", "cataclysm:soul_render:axe", "warriorsofpastepoch:musket:bow", "warriorswofpastepoch:pistol:bow", "warriorswofpastepoch:surgical_saw:bow", "irons_spellboks:blood_staff:staff", "irons_spellbooks:graybeard_staff:staff", "irons_spellbooks:ice_staff:staff", "alexscaves:raygun:bow", "alexscaves:sea_staff:staff", "alexscaves:sugar_staff:staff", "alexscaves:dreadbow:bow", "simplyswords:iron_greataxe:axe", "simplyswords:gold_greataxe:axe", "simplyswords:diamond_greataxe:axe", "simplyswords:netherite_greataxe:axe", "simplyswords:runic_greataxe:axe", "simplyswords:iron_cutlass:dagger", "simplyswords:gold_cutlass:dagger", "simplyswords:diamond_cutlass:dagger", "simplyswords:netherite_cutlass:dagger", "simplyswords:runic_cutlass:dagger", "simplyswords:iron_rapier:dagger", "simplyswords:gold_rapier:dagger", "simplyswords:diamond_rapier:dagger", "simplyswords:netherite_rapier:dagger", "simplyswords:runic_rapier:dagger", "simplyswords:iron_sai:dagger", "simplyswords:gold_sai:dagger", "simplyswords:diamond_sai:dagger", "simplyswords:netherite_sai:dagger", "simplyswords:runic_sai:dagger", "simplyswords:iron_chakram:dagger", "simplyswords:gold_chakram:dagger", "simplyswords:diamond_chakram:dagger", "simplyswords:netherite_chakram:dagger", "simplyswords:runic_chakram:dagger", "simplyswords:iron_spear:spear", "simplyswords:gold_spear:spear", "simplyswords:netherite_spear:spear", "simplyswords:runic_spear:spear", "simplyswords:diamond_spear:spear", "simplyswords:iron_glaive:spear", "simplyswords:gold_glaive:spear", "simplyswords:diamond_glaive:spear", "simplyswords:netherite_glaive:spear", "simplyswords:runic_glaive:spear", "simplyswords:iron_halberd:axe", "simplyswords:gold_halberd:axe", "simplyswords:diamond_halberd:axe", "simplyswords:netherite_halberd:axe", "simplyswords:runic_halberd:axe", "simplyswords:iron_scythe:scythe", "simplyswords:gold_scythe:scythe", "simplyswords:diamond_scythe:scythe", "simplyswords:netherite_scythe:scythe", "simplyswords:runic_scythe:scythe", "simplyswords:iron_greathammer:hammer", "simplyswords:gold_greathammer:hammer", "simplyswords:diamond_greathammer:hammer", "simplyswords:netherite_greathammer:hammer", "simplyswords:runic_greathammer:hammer", "simplyswords:iron_claymore:greatsword", "simplyswords:gold_claymore:greatsword", "simplyswords:diamond_claymore:greatsword", "simplyswords:netherite_claymore:greatsword", "simplyswords:runic_claymore:greatsword", "simplyswords:iron_warglaive:dagger", "simplyswords:gold_warglaive:dagger", "simplyswords:diamond_warglaive:dagger", "simplyswords:netherite_warglaive:dagger", "simplyswords:runic_warglaive:dagger", "simplyswords:gold_warglaive:dagger", "born_in_chaos_v1:nightmare_scythe:scythe", "born_in_chaos_v1:skullbreaker_hammer:hammer", "born_in_chaos_v1:darkwarblade:greatsword", "born_in_chaos_v1:shell_mace:hammer", "born_in_chaos_v1:trident_hayfork:spear", "born_in_chaos_v1:intoxicating_dagger:dagger", "born_in_chaos_v1:soul_cutlass:dagger", "cataclysm:athame:dagger", "call_of_yucatan:obsidian_tecpalt:dagger", "call_of_yucatan:obsidian_spear:spear", "call_of_yucatan:macuahuitl:axe", "aquamirae:coral_lance:spear", "aquamirae:whisper_of_the_abyss:spear", "samurai_dynasty:naginata:spear", "samurai_dynasty:naginata_netherite:spear", "samurai_dynasty:nagamaki:spear", "samurai_dynasty:nagamaki_netherite:spear", "samurai_dynasty:kamayari:spear", "samurai_dynasty:kamayari_netherite:spear", "samurai_dynasty:tonbukiri:spear", "samurai_dynasty:tonbukiri_netherite:spear", "samurai_dynasty:odachi:greatsword", "samurai_dynasty:odachi_netherite:greatsword", "samurai_dynasty:sai:dagger", "samurai_dynasty:kunai:dagger", "samurai_dynasty:shuko:gauntlet", "samurai_dynasty:shuko_netherite:gauntlet", "samurai_dynasty:wakizashi:dagger", "samurai_dynasty:wakizashi_netherite:dagger"]
	#Stops items from being used in maps/adventuremaps. This is used for items that allow cheesing mechanics like teleporation items mostly.
	disabled_items_in_maps = ["minecraft:ender_pearl", "minecraft:chorus_fruit"]
	SOUL_CLEANER_ITEM_BLACKLIST = ["minecraft:diamond"]

	#These are just default values for the Mine and slash Hub > features
	[general."Default Feature Configs"]
		cast_fail_messages = true
		mob_death_messages = false
		exp_chat_messages = false
		damage_messages = false
		profession_exp_messages = false
		auto_pve = false
		aggressive_summons = true
		stat_order_test = false
		damage_conflict_check = false
		everyone_is_ally = false

